# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-24 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='threshold',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
