# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-24 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20190325_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
