# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-31 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_alarm_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='pid',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
